[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["rm -rf ~/.cache/pip", "rm -rf /tmp/*"]

[start]
cmd = "uvicorn chatbot:app --host 0.0.0.0 --port $PORT"
